// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkTQ0aMlkyRBFSnk-hhN9eDeV5RH69oRs',
    appId: '1:223090464089:web:236e6c70a96d25cf736848',
    messagingSenderId: '223090464089',
    projectId: 'umrahapp-8f803',
    authDomain: 'umrahapp-8f803.firebaseapp.com',
    storageBucket: 'umrahapp-8f803.firebasestorage.app',
    measurementId: 'G-NR38LNHSXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfLP1Zndyh00zo3wp6sgIXyQknlq29-yE',
    appId: '1:223090464089:android:88165755b89439d2736848',
    messagingSenderId: '223090464089',
    projectId: 'umrahapp-8f803',
    storageBucket: 'umrahapp-8f803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtW5yX-NdakiUAVXSKFpE_H9EJhh49gAk',
    appId: '1:223090464089:ios:d929d7c9f393a86e736848',
    messagingSenderId: '223090464089',
    projectId: 'umrahapp-8f803',
    storageBucket: 'umrahapp-8f803.firebasestorage.app',
    iosBundleId: 'com.example.umrahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtW5yX-NdakiUAVXSKFpE_H9EJhh49gAk',
    appId: '1:223090464089:ios:d929d7c9f393a86e736848',
    messagingSenderId: '223090464089',
    projectId: 'umrahapp-8f803',
    storageBucket: 'umrahapp-8f803.firebasestorage.app',
    iosBundleId: 'com.example.umrahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkTQ0aMlkyRBFSnk-hhN9eDeV5RH69oRs',
    appId: '1:223090464089:web:f5988c9f7c96baa4736848',
    messagingSenderId: '223090464089',
    projectId: 'umrahapp-8f803',
    authDomain: 'umrahapp-8f803.firebaseapp.com',
    storageBucket: 'umrahapp-8f803.firebasestorage.app',
    measurementId: 'G-VFV08TJ8X3',
  );
}
